#!/bin/bash

echo "================================="
echo "MyBatis Plus CRUD 项目结构展示"
echo "================================="

echo ""
echo "📁 项目目录结构："
echo "├── pom.xml                           # Maven配置文件"
echo "├── src/main/java/com/example/mybatisplus/"
echo "│   ├── entity/"
echo "│   │   └── User.java                 # 用户实体类"
echo "│   ├── mapper/"
echo "│   │   └── UserMapper.java           # 数据访问层接口"
echo "│   ├── service/"
echo "│   │   ├── UserService.java          # 业务逻辑接口"
echo "│   │   └── impl/"
echo "│   │       └── UserServiceImpl.java  # 业务逻辑实现"
echo "│   ├── controller/"
echo "│   │   └── UserController.java       # 控制器层"
echo "│   ├── config/"
echo "│   │   └── MybatisPlusConfig.java    # MyBatis Plus配置"
echo "│   └── MybatisPlusApplication.java   # Spring Boot启动类"
echo "├── src/main/resources/"
echo "│   ├── application.yml               # 应用配置文件"
echo "│   ├── mapper/"
echo "│   │   └── UserMapper.xml            # MyBatis XML映射文件"
echo "│   ├── schema.sql                    # 数据库表结构"
echo "│   └── data.sql                      # 测试数据"
echo "└── src/test/java/"
echo "    └── UserControllerTest.java       # 测试类"

echo ""
echo "🚀 功能特性："
echo "✅ 完整的CRUD操作（增删改查）"
echo "✅ 分页查询和条件查询"
echo "✅ 批量操作（批量删除、批量更新状态）"
echo "✅ 逻辑删除（软删除）"
echo "✅ 乐观锁（版本控制）"
echo "✅ 自动填充（创建时间、更新时间）"
echo "✅ 数据校验（用户名、邮箱、手机号唯一性检查）"
echo "✅ 异常处理和统一返回格式"
echo "✅ RESTful API设计"
echo "✅ 支持H2内存数据库和MySQL"

echo ""
echo "📋 API接口列表："
echo "GET    /api/users/page                # 分页查询用户列表"
echo "GET    /api/users/{id}                # 根据ID查询用户详情"
echo "GET    /api/users/username/{username} # 根据用户名查询用户"
echo "GET    /api/users/status/{status}     # 根据状态查询用户列表"
echo "POST   /api/users                     # 创建用户"
echo "PUT    /api/users/{id}                # 更新用户信息"
echo "DELETE /api/users/{id}                # 删除用户（逻辑删除）"
echo "DELETE /api/users/batch               # 批量删除用户"
echo "PUT    /api/users/status/batch        # 批量更新用户状态"
echo "GET    /api/users/check/username      # 检查用户名是否存在"
echo "GET    /api/users/check/email         # 检查邮箱是否存在"
echo "GET    /api/users/check/phone         # 检查手机号是否存在"
echo "GET    /api/users/statistics          # 统计用户数量（按状态分组）"

echo ""
echo "🔧 技术栈："
echo "• Spring Boot 2.7.18"
echo "• MyBatis Plus 3.5.3.1"
echo "• H2 Database (默认)"
echo "• MySQL (可选)"
echo "• Lombok"
echo "• Maven"

echo ""
echo "📖 使用说明："
echo "1. 确保已安装JDK 11+和Maven 3.6+"
echo "2. 运行 'mvn clean compile' 编译项目"
echo "3. 运行 'mvn spring-boot:run' 启动项目"
echo "4. 访问 http://localhost:8080 查看应用"
echo "5. 访问 http://localhost:8080/h2-console 查看数据库"
echo "6. 使用Postman或其他工具测试API接口"

echo ""
echo "💡 扩展建议："
echo "• 可以基于此模板快速创建其他实体类的CRUD操作"
echo "• 可以添加Redis缓存提升性能"
echo "• 可以集成Spring Security实现权限控制"
echo "• 可以添加Swagger生成API文档"
echo "• 可以添加日志记录和监控"

echo ""
echo "================================="
echo "项目创建完成！🎉"
echo "================================="